name = "timetable-425m-tgbot"
main = "worker.js"
compatibility_date = "2025-11-14"

kv_namespaces = [
  { binding = "SETTINGS_KV", id = "YOUR_KV_NAMESPACE_ID", preview_id = "YOUR_PREVIEW_KV_NAMESPACE_ID" }
]

[triggers]
crons = ["30 1 * * *"]
